[package]
name = "kaspa-wallet-pskt"
keywords = ["kaspa", "wallet", "pskt", "psbt", "bip-370"]
description = "Partially Signed Kaspa Transaction"
categories = ["cryptography::cryptocurrencies"]
rust-version.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
include.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
kaspa-bip32.workspace = true
kaspa-consensus-core.workspace = true

derive_builder.workspace = true
secp256k1.workspace = true
serde.workspace = true
serde-value.workspace = true
thiserror.workspace = true
